In [76]:
import pandas as pd
rt = pd.read_csv('ratings.csv')
rt

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [89]:
mv = pd.read_csv('movies.csv', sep = ',', quotechar='"')
mv.head(50)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
10,"11,""American President, The (1995)"",Comedy|Dra...",NaN,NaN
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
12,13,Balto (1995),Adventure|Animation|Children
13,14,Nixon (1995),Drama
14,15,Cutthroat Island (1995),Action|Adventure|Romance
15,16,Casino (1995),Crime|Drama
16,17,Sense and Sensibility (1995),Drama|Romance
17,18,Four Rooms (1995),Comedy
18,19,Ace Ventura: When Nature Calls (1995),Comedy
19,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller
20,21,Get Shorty (1995),Comedy|Crime|Thriller
21,22,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller
22,23,Assassins (1995),Action|Crime|Thriller
23,24,Powder (1995),Drama|Sci-Fi
24,25,Leaving Las Vegas (1995),Drama|Romance
25,26,Othello (1995),Drama
26,27,Now and Then (1995),Children|Drama
27,28,Persuasion (1995),Drama|Romance
28,"29,""City of Lost Children, The (Cité des enfan...",NaN,NaN
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Crime|Drama
30,31,Dangerous Minds (1995),Drama
31,32,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller
32,34,Babe (1995),Children|Drama
33,36,Dead Man Walking (1995),Crime|Drama
34,38,It Takes Two (1995),Children|Comedy
35,39,Clueless (1995),Comedy|Romance
36,"40,""Cry, the Beloved Country (1995)"",Drama",NaN,NaN
37,41,Richard III (1995),Drama|War
38,42,Dead Presidents (1995),Action|Crime|Drama
39,43,Restoration (1995),Drama
40,44,Mortal Kombat (1995),Action|Adventure|Fantasy
41,45,To Die For (1995),Comedy|Drama|Thriller
42,46,How to Make an American Quilt (1995),Drama|Romance
43,47,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
44,48,Pocahontas (1995),Animation|Children|Drama|Musical|Romance
45,49,When Night Is Falling (1995),Drama|Romance
46,"50,""Usual Suspects, The (1995)"",Crime|Mystery|...",NaN,NaN
47,52,Mighty Aphrodite (1995),Comedy|Drama|Romance
48,53,Lamerica (1994),Adventure|Drama
49,"54,""Big Green, The (1995)"",Children|Comedy",NaN,NaN

In [83]:
import csv
mvv = pd.read_csv('movies.csv', sep=',', quoting=csv.QUOTE_ALL, quotechar="\"")
mvv.head(13)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
10,"11,""American President, The (1995)"",Comedy|Dra...",NaN,NaN
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
12,13,Balto (1995),Adventure|Animation|Children

In [11]:
mv.movieId.count()

9742

Какое минимальное значение принимает выставленная оценка в датасете ratings?

In [2]:
rt.rating.min()

0.5

In [67]:
import pandas as pd
ratings = pd.read_csv('ratings.csv')
movies = pd.read_csv('movies.csv')
joined = ratings.merge(movies, how='left', on = 'movieId')
display(joined)

ValueError: You are trying to merge on int64 and object columns. If you wish to proceed you should use pd.concat

In [12]:
joined = rt.merge(mv, on='movieId', how='left')
joined.head()

ValueError: You are trying to merge on int64 and object columns. If you wish to proceed you should use pd.concat