In [32]:
import pandas as pd
rt = pd.read_csv('ratings (6).xls')
rt.head(10)

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931
5       1       70     3.0  964982400
6       1      101     5.0  964980868
7       1      110     4.0  964982176
8       1      151     5.0  964984041
9       1      157     5.0  964984100

In [12]:
mv = pd.read_csv('movies (6).xls')
mv.head(50)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
10,11,"American President, The (1995)",Comedy|Drama|Romance
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
12,13,Balto (1995),Adventure|Animation|Children
13,14,Nixon (1995),Drama
14,15,Cutthroat Island (1995),Action|Adventure|Romance
15,16,Casino (1995),Crime|Drama
16,17,Sense and Sensibility (1995),Drama|Romance
17,18,Four Rooms (1995),Comedy
18,19,Ace Ventura: When Nature Calls (1995),Comedy
19,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller
20,21,Get Shorty (1995),Comedy|Crime|Thriller
21,22,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller
22,23,Assassins (1995),Action|Crime|Thriller
23,24,Powder (1995),Drama|Sci-Fi
24,25,Leaving Las Vegas (1995),Drama|Romance
25,26,Othello (1995),Drama
26,27,Now and Then (1995),Children|Drama
27,28,Persuasion (1995),Drama|Romance
28,29,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Crime|Drama
30,31,Dangerous Minds (1995),Drama
31,32,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller
32,34,Babe (1995),Children|Drama
33,36,Dead Man Walking (1995),Crime|Drama
34,38,It Takes Two (1995),Children|Comedy
35,39,Clueless (1995),Comedy|Romance
36,40,"Cry, the Beloved Country (1995)",Drama
37,41,Richard III (1995),Drama|War
38,42,Dead Presidents (1995),Action|Crime|Drama
39,43,Restoration (1995),Drama
40,44,Mortal Kombat (1995),Action|Adventure|Fantasy
41,45,To Die For (1995),Comedy|Drama|Thriller
42,46,How to Make an American Quilt (1995),Drama|Romance
43,47,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
44,48,Pocahontas (1995),Animation|Children|Drama|Musical|Romance
45,49,When Night Is Falling (1995),Drama|Romance
46,50,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
47,52,Mighty Aphrodite (1995),Comedy|Drama|Romance
48,53,Lamerica (1994),Adventure|Drama
49,54,"Big Green, The (1995)",Children|Comedy

In [13]:
mv.movieId.count()

9742

Какое минимальное значение принимает выставленная оценка в датасете ratings?

In [14]:
rt.rating.min()

0.5

In [16]:
len(rt) == len(joined)

True

In [29]:
joinedd = rt.merge(mv, on='movieId', how='left')
#joinedd[joinedd.movieId == 31]
joinedd.head(30)

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
5,1,70,3.0,964982400,From Dusk Till Dawn (1996),Action|Comedy|Horror|Thriller
6,1,101,5.0,964980868,Bottle Rocket (1996),Adventure|Comedy|Crime|Romance
7,1,110,4.0,964982176,Braveheart (1995),Action|Drama|War
8,1,151,5.0,964984041,Rob Roy (1995),Action|Drama|Romance|War
9,1,157,5.0,964984100,Canadian Bacon (1995),Comedy|War
10,1,163,5.0,964983650,Desperado (1995),Action|Romance|Western
11,1,216,5.0,964981208,Billy Madison (1995),Comedy
12,1,223,3.0,964980985,Clerks (1994),Comedy
13,1,231,5.0,964981179,Dumb & Dumber (Dumb and Dumber) (1994),Adventure|Comedy
14,1,235,4.0,964980908,Ed Wood (1994),Comedy|Drama
15,1,260,5.0,964981680,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi
16,1,296,3.0,964982967,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller
17,1,316,3.0,964982310,Stargate (1994),Action|Adventure|Sci-Fi
18,1,333,5.0,964981179,Tommy Boy (1995),Comedy
19,1,349,4.0,964982563,Clear and Present Danger (1994),Action|Crime|Drama|Thriller
20,1,356,4.0,964980962,Forrest Gump (1994),Comedy|Drama|Romance|War
21,1,362,5.0,964982588,"Jungle Book, The (1994)",Adventure|Children|Romance
22,1,367,4.0,964981710,"Mask, The (1994)",Action|Comedy|Crime|Fantasy
23,1,423,3.0,964982363,Blown Away (1994),Action|Thriller
24,1,441,4.0,964980868,Dazed and Confused (1993),Comedy
25,1,457,5.0,964981909,"Fugitive, The (1993)",Thriller
26,1,480,4.0,964982346,Jurassic Park (1993),Action|Adventure|Sci-Fi|Thriller
27,1,500,3.0,964981208,Mrs. Doubtfire (1993),Comedy|Drama
28,1,527,5.0,964984002,Schindler's List (1993),Drama|War
29,1,543,4.0,964981179,So I Married an Axe Murderer (1993),Comedy|Romance|Thriller